# Generated by Django 2.1.5 on 2019-01-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('guest', models.CharField(max_length=100)),
                ('room', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('family', 'Family')], max_length=20)),
                ('price', models.IntegerField()),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], max_length=20)),
                ('remark', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
    ]
