# Generated by Django 2.1.5 on 2019-01-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_restandbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.CharField(choices=[('comfort 1', 'Comfort 1'), ('comfort 2', 'Comfort 2'), ('comfort 3', 'Comfort 3'), ('standard', 'Standard'), ('superior', 'Superior'), ('standard superior', 'Standard Superior '), ('classic superior', 'Classic Superior'), ('executives suites', 'Executives Suites')], max_length=20),
        ),
    ]
